swagger: "2.0"
info:
  description: "This is a sample payment service - MoneyPal."
  version: "1.0.0"
  title: "MoneyPal"
  contact:
    email: "jacek.spolnik@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "moneypal.herokuapp.com"
basePath: "/api/v1"
tags:
- name: "payment"
  description: "Everything about payments"
- name: "account"
  description: "Everything about accounts"
schemes:
- "https"
paths:
  /payments:
    post:
      tags:
      - "payment"
      summary: "Execute new payment"
      description: ""
      operationId: "executePayment"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Execute payment request"
        required: true
        schema:
          $ref: "#/definitions/ExecutePaymentApiRequestV1"
      responses:
        200:
          description: "Payment completed successfully"
          schema:
            $ref: "#/definitions/ExecutePaymentApiResponseV1"
    get:
      tags:
      - "payment"
      summary: "Get all executed payments"
      description: ""
      operationId: "findAllPayments"
      produces:
      - "application/json"
      responses:
        200:
          description: "Successful Operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Payment"
  /accounts:
    post:
      tags:
      - "account"
      summary: "Register new account"
      description: ""
      operationId: "createAccount"
      produces:
      - "application/json"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Create new account request"
        required: true
        schema:
          $ref: "#/definitions/CreateAccountApiRequestV1"
      responses:
        200:
          description: "Account created successfully"
          schema:
            $ref: "#/definitions/CreateAccountApiResponseV1"
  /accounts/{accountId}:
    get:
      tags:
      - "account"
      summary: "Get user accounts"
      description: ""
      operationId: "findUserAccounts"
      produces:
      - "application/json"
      parameters:
      - name: "accountId"
        in: "path"
        description: "Account ID"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Account"
        404:
          description: "Not found"
definitions:
  ExecutePaymentApiRequestV1:
    type: "object"
    properties:
      userId:
        type: "string"
      accountFrom:
        type: "string"
      accountTo:
        type: "string"
      amount:
        $ref: "#/definitions/Money"
      trackId:
        type: "string"
  ExecutePaymentApiResponseV1:
    type: "object"
    properties:
      userId:
        type: "string"
      status:
        type: "string"
        enum:
        - "COMPLETED"
        - "REJECTED"
      trackId:
        type: "string"
  CreateAccountApiRequestV1:
    type: "object"
    properties:
      userId:
        type: "string"
      accountId:
        type: "string"
      initialBalance:
        $ref: "#/definitions/Money"
      trackId:
        type: "string"
  CreateAccountApiResponseV1:
    type: "object"
    properties:
      accountId:
        type: "string"
      status:
        type: "string"
        enum:
        - "CREATED"
        - "REJECTED"
      trackId:
        type: "string"
  Money:
    type: "object"
    properties:
      currency:
        type: "string"
      amount:
        type: "number"
        format: "double"
  Payment:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      userId:
        type: "string"
      accountFrom:
        type: "string"
      accountTo:
        type: "string"
      amount:
        $ref: "#/definitions/Money"
      trackId:
        type: "string"
      receivedAtUTC:
        type: "string"
        format: "date-time"
  Account:
    type: "object"
    properties:
      id:
        type: "string"
      userId:
        type: "string"
      accountId:
        type: "string"
      balance:
        $ref: "#/definitions/Money"
externalDocs:
  description: "Find out more about MoneyPal"
  url: "https://github.com/spolnik/payment-service"